name: FVPVideo
description: Bindings for AVPlayer and related classes.
language: objc
output:
  bindings: 'lib/src/ffi_bindings.dart'
  # Currently not built; hopefully can be removed via method filtering once
  # implemented since we probably don't actually need them.
  objc-bindings: 'darwin/ffi_bindings.dart.m'
headers:
  entry-points:
    - '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AVFoundation.framework/Versions/A/Headers/AVFoundation.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPDefaultAVFactory.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPVideoPlayer.h'
exclude-all-by-default: true
objc-interfaces:
  include:
    - 'AVAudioSession'
    - 'AVPlayer'
    - 'FVPDefaultAVFactory'
    - 'FVPVideoPlayer'
enums:
  include:
    - 'AVAudioSessionCategoryOptions'
globals:
  include:
    - 'AVAudioSessionCategoryPlayback'
