name: FVPVideo
description: Bindings for AVPlayer and related classes.
language: objc
output:
  bindings: 'lib/src/ffi_bindings.dart'
  objc-bindings: 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/ffi_bindings.dart.m'
headers:
  entry-points:
    # See https://github.com/dart-lang/native/issues/471
    - '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AVFoundation.framework/Versions/A/Headers/AVFoundation.h'
    - '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/A/Headers/Foundation.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPDefaultAVFactory.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPDefaultDisplayLinkFactory.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPVideoPlayer.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPVideoPlayerDelegate.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPBlockAdapterVideoPlayerDelegate.h'
exclude-all-by-default: true
objc-interfaces:
  include:
    - 'AVAudioSession'
    - 'AVPlayer'
    - 'FVPDefaultAVFactory'
    - 'FVPDefaultDisplayLinkFactory'
    - 'FVPVideoPlayer'
    - 'FVPBlockAdapterVideoPlayerDelegate'
    - 'NSNotificationCenter'
functions:
  include:
    - 'CMTimeMake'
enums:
  include:
    - 'AVAudioSessionCategoryOptions'
globals:
  include:
    - 'AVAudioSessionCategoryPlayback'
    - 'AVPlayerItemDidPlayToEndTimeNotification'
    - 'AVMediaTypeVideo'
    - 'kCMTimeZero'
