name: FVPVideo
description: Bindings for AVPlayer and related classes.
language: objc
output:
  bindings: 'lib/src/ffi_bindings.dart'
  objc-bindings: 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/ffi_bindings.dart.m'
headers:
  entry-points:
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FFIHeaders.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPBlockKeyValueObserver.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPDisplayLink.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPFrameUpdater.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPPluginAPIProxy.h'
    - 'darwin/video_player_avfoundation/Sources/video_player_avfoundation/include/video_player_avfoundation/FVPVideoPlayer.h'
exclude-all-by-default: true
objc-interfaces:
  include:
    - 'AVAudioSession'
    - 'AVMutableVideoCompositionInstruction'
    - 'AVMutableVideoCompositionLayerInstruction'
    - 'AVPlayer'
    - 'AVPlayerLayer'
    - 'FVPBlockKeyValueObserver'
    - 'FVPDisplayLink'
    - 'FVPFrameUpdater'
    - 'FVPPluginAPIProxy'
    - 'FVPVideoPlayer'
    - 'NSNotificationCenter'
functions:
  include:
    - 'CMTimeMake'
    - 'CMTimeRangeMake'
    - 'GLKMathRadiansToDegrees'
enums:
  include:
    - 'AVAudioSessionCategoryOptions'
globals:
  include:
    - 'AVAudioSessionCategoryPlayback'
    - 'AVPlayerItemDidPlayToEndTimeNotification'
    - 'AVMediaTypeVideo'
    - 'kCMTimeZero'
    - 'kCVPixelBufferPixelFormatTypeKey'
    - 'kCVPixelBufferIOSurfacePropertiesKey'
structs:
  include:
    - 'CGFloat'
typedefs:
  include:
    - 'CFStringRef'
unnamed-enums:
  include:
    - 'kCVPixelFormatType.*'
